#!/usr/bin/sh

dbus-update-activation-environment --all

# Configure workspaces and monitor
bspc monitor DP-4   -d  1  2  3  4  5  6  7  8
bspc monitor HDMI-0 -d 11 12 13 14 15 16 17 18

# Start the keybinds deamon
export SXHKD_SHELL=sh
grep -x sxhkd > /dev/null || sxhkd &

# General settings
bspc config split_ratio      0.50
bspc config single_monocle	 true

# Place the focus where the mouse moves
bspc config focus_follows_pointer true

# The pointer move to the center of the focused window
bspc config pointer_follows_focus true

# Gaps settings
bspc config border_width         2
bspc config window_gap           5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border color
bspc config normal_border_color \#45454A
bspc config active_border_color \#45454A
bspc config focused_border_color \#77C3F1

# Set coursor size
xsetroot -xcf ~/.icons/default/cursors/left_ptr 24

setxkbmap it

# Run auto start application
~/.config/bspwm/autostart.sh
